a = input('Digite algo ')
print('O tipo primitivo do valor é{}'.format(type(a)))
print('É numérico?{}'.format(a.isnumeric()))
print('É alfabetico?{}'.format(a.isalpha()))
print(f'É alfanumérico?{a.isalnum()}')
print(f'É tudo minúsculo?{a.islower()}')
print(f'É tudo maiúsculo?{a.isupper()}')
print(f'É tudo espaço?{a.isspace()}')
print(f'É capitalizada?{a.istitle()}')
