a = input('Digite algo ')
print('O tipo primitivo do valor é', type(a))
print('É numérico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('É minúsula?', a.islower())
print('É maiúscula', a.isupper())
print('É somente espaço?', a.isspace())
print('É capitalizada?', a.istitle())
